version: '3'
services:
  server:
    container_name: shappables-server
    build: packages/server
    environment:
      DB_URI: $DB_URI
      ES_ENDPOINT: http://es01:9200
      AWS_PROFILE: $AWS_PROFILE
      HOME: "/home"
    command: ["./wait-for-it.sh", "es01:9200", "--", "npm", "run", "start:prod"]
    volumes:
      - $HOME/.aws/credentials:/home/.aws/credentials:ro
    networks:
      - frontend
      - elasticsearch
    ports:
      - 3000:3000
    depends_on: [ elasticsearch ]

  client:
    container_name: shappables-client
    build: packages/client
    networks:
      - frontend
    ports:
      - 80:80
    depends_on: [ server ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elasticsearch
    ports:
      - 9200:9200

networks:
  frontend:
  elasticsearch:
